sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        groups:
            administration:
                label: ADministration
                items:
                    - admin.user
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    options:
        legacy_twig_text_extension: false

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [ admin ]
